Strict namespace{

Script "GulagRestart" (void) NET
{
    LogDebug(__SCRIPT__ + " : Restarting the game..");
    ResetMap();
}

Script "ForceReady" (int pnum) NET
{
    if(pready[pnum] == false)
    {
        LogDebug(__SCRIPT__ + " : Forced Player \ck" + str(pnum) + " Ready");
        pready[pnum] = true;
    }
    else
    {
        LogDebug(__SCRIPT__ + " : Forced Player \ck" + str(pnum) + " Unready");
        pready[pnum] = false;
    }
}

}